<Project>
	<PropertyGroup Condition="'$(MSBuildProjectName)' == 'ComputeSharp' or '$(MSBuildProjectName)' == 'ComputeSharp.Core'">
		<BaseOutputPath>$(MSBuildProjectDirectory)\bin\CrystallineGrowth\</BaseOutputPath>
		<BaseIntermediateOutputPath>$(MSBuildProjectDirectory)\obj\CrystallineGrowth\</BaseIntermediateOutputPath>
		<MSBuildProjectExtensionsPath>$(MSBuildProjectDirectory)\obj\</MSBuildProjectExtensionsPath>
		<DefaultItemExcludes>$(DefaultItemExcludes);$(MSBuildProjectDirectory)\obj\**</DefaultItemExcludes>
	</PropertyGroup>
	<PropertyGroup Condition="'$(MSBuildProjectName)' == 'ComputeSharp'">
		<AssemblyName>CrystallineGrowth.ComputeSharp</AssemblyName>
	</PropertyGroup>
	<PropertyGroup Condition="'$(MSBuildProjectName)' == 'ComputeSharp.Core'">
		<AssemblyName>CrystallineGrowth.ComputeSharp.Core</AssemblyName>
	</PropertyGroup>
</Project>
